language: node_js
node_js:
  - '0.10'
branches:
  except:
    - gh-pages
after_sucess:
  - npm run gh-pages-travis
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Peter Halliday"
    - GIT_EMAIL="pghalliday@gmail.com"
    - SOURCE_DIR="docs"
    - DEPLOY_BRANCH="master"