name: Juliane Albuquerque
author: https://plus.google.com/106816029032156931516
timezone: America/Sao_Paulo

exclude: ["README.md", "Makefile", ".gitignore"]
pygments: true
permalink: /:title
url: http://julianealbuquerque.com.br
baseurl: /
lsi: false
dev: false