name: Juliane Albuquerque
author: Juliane Albuquerque
timezone: America/Sao_Paulo

exclude: ["README.md", "Makefile", ".gitignore"]
pygments: true
permalink: /:title
url: http://julianealbuquerque.com.br
baseurl: /julianealbuquerque.com.br
lsi: false
dev: false